workaround missing builtins in Apple Clang
treat Apple Clang like MSVC and punt on these builtins...

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCL_TARGET_OPENCL_VERSION=220 -DXPTI_ENABLE_INSTRUMENTATION -DXPTI_STATIC_LIBRARY -D_DEBUG -D_GLIBCXX_ASSERTIONS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/sycl/source -I/Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/source -Iinclude -I/Users/jrhammon/Work/OpenCL/ISYCL/llvm/llvm/include -I/Users/jrhammon/Work/OpenCL/ISYCL/llvm/xpti/include -I/Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/include -Itools/sycl/OpenCL/inc -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -Wall -Wextra -Wno-deprecated-declarations -Werror -O3  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -UNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden -std=c++14 -MD -MT tools/sycl/source/CMakeFiles/sycl_object.dir/detail/accessor_impl.cpp.o -MF tools/sycl/source/CMakeFiles/sycl_object.dir/detail/accessor_impl.cpp.o.d -o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/accessor_impl.cpp.o -c /Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/source/detail/accessor_impl.cpp
In file included from /Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/source/detail/accessor_impl.cpp:9:
In file included from /Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/include/CL/sycl/detail/accessor_impl.hpp:11:
In file included from /Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/include/CL/sycl/access/access.hpp:10:
/Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/include/CL/sycl/detail/common.hpp:50:34: error: use of undeclared identifier '__builtin_FILE'
  current(const char *fileName = __builtin_FILE(),
                                 ^
/Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/include/CL/sycl/detail/common.hpp:51:34: error: use of undeclared identifier '__builtin_FUNCTION'
          const char *funcName = __builtin_FUNCTION(),
                                 ^
/Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/include/CL/sycl/detail/common.hpp:52:34: error: use of undeclared identifier '__builtin_LINE'
          unsigned long lineNo = __builtin_LINE(),
                                 ^
/Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/include/CL/sycl/detail/common.hpp:50:23: error: unused parameter 'fileName' [-Werror,-Wunused-parameter]
  current(const char *fileName = __builtin_FILE(),
                      ^
/Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/include/CL/sycl/detail/common.hpp:51:23: error: unused parameter 'funcName' [-Werror,-Wunused-parameter]
          const char *funcName = __builtin_FUNCTION(),
                      ^
/Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/include/CL/sycl/detail/common.hpp:52:25: error: unused parameter 'lineNo' [-Werror,-Wunused-parameter]
          unsigned long lineNo = __builtin_LINE(),
                        ^
/Users/jrhammon/Work/OpenCL/ISYCL/llvm/sycl/include/CL/sycl/detail/common.hpp:50:3: error: no return statement in constexpr function
  current(const char *fileName = __builtin_FILE(),
  ^
7 errors generated.

Signed-off-by: Hammond, Jeff R <jeff.r.hammond@intel.com>